//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARCLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscussionMessage
    {
        public string messageId { get; set; }
        public string message { get; set; }
        public string userId { get; set; }
        public int threadId { get; set; }
    
        public virtual DiscussionThread DiscussionThread { get; set; }
        public virtual User User { get; set; }
    }
}
